### ISSUE TITLE
Global Header design

### ISSUE THREAD

**Issue by schluchter** [fabric-design/scss#15]
Do it!!!

**Comment by myueksel** [comment]
New HeaderDesign proposal.

see more versions on InVision:
https://zalando.invisionapp.com/d/#/projects/prototypes/10621613/screens

![headerdesign_2](https://cloud.githubusercontent.com/assets/25901307/24303058/e3d2a5aa-10b4-11e7-9b0a-90a7e3955d66.png)

**Comment by faboweb** [comment]
@myueksel I like it. Where is the language switch going? I suppose the grid item redirects you to some kind of dashboard? Or how is the flow to other applications?

**Comment by myueksel** [comment]
Language switch should stay on top right... in the same line as the other icons. Actually not sure in which order but I'll create an example ASAP.
Other applications are supposed to reach via the first icon on top right (the square one).

**Comment by faboweb** [comment]
Comment: It's sooooooo bluuuuueeeee

Idea: Have a color for each application to immediately know where you as a user are.

**Comment by myueksel** [comment]
of course, we'll discuss your proposal... therefore I've created some examples. 
Here  the link to InVision: https://zalando.invisionapp.com/d/main#/projects/prototypes/10621613/screens

screenshoots:

![screen shot 2017-03-28 at 16 29 38](https://cloud.githubusercontent.com/assets/25901307/24410846/684dcfae-13d4-11e7-9219-be7c5c6e4933.png)

![screen shot 2017-03-28 at 16 29 48](https://cloud.githubusercontent.com/assets/25901307/24410853/6c739424-13d4-11e7-9bf5-479a56272484.png)

**Comment by faboweb** [comment]
I personally like the once with the accent colors only more the the bulky full colored once.

**Comment by fokusferit** [comment]
I have to admit I like it when the every application gets it's own header color (not white + accent), e.g. it reminds me of Outlook :) 

![screen shot 2017-03-29 at 16 02 36](https://cloud.githubusercontent.com/assets/1215719/24458525/78a5c224-1499-11e7-8d49-d200b2a1a5d0.png)

**Comment by myueksel** [comment]
Latest proposal 2rem hight header. Color is not defined yet

![screen shot 2017-05-18 at 11 56 55](https://cloud.githubusercontent.com/assets/25901307/26197057/3be5c088-3bc1-11e7-8b96-31fbbef0a8ab.png)

![screen shot 2017-05-18 at 11 58 16](https://cloud.githubusercontent.com/assets/25901307/26197077/4bfaca22-3bc1-11e7-8914-710ee6f8a1a0.png)

**Comment by fragsalat** [comment]
Loooks pretty nice but in my eyes it could be even higher. Lets see how it looks when it was implemented :)

**Comment by faboweb** [comment]
+1 for higher. It looks a little lost and the icons look squashed. But no veto. In general nice.

**Comment by myueksel** [comment]
Updated menu/header and added specification...
Invision:
https://zalando.invisionapp.com/d/main/#/projects/prototypes/10621613

Vertical menu:
![vertical menu v6](https://cloud.githubusercontent.com/assets/25901307/26410386/644c4e98-40a3-11e7-99c6-32b4e3dce161.png)

Horizontal menu:
![horizontal menu v5](https://cloud.githubusercontent.com/assets/25901307/26410391/68711b84-40a3-11e7-9428-7007bc6dd890.png)

**Comment by schluchter** [comment]
@myueksel Please update the color scheme documentation to include accessibility concerns.

**Comment by schluchter** [comment]
@AdrianDampc Please make a proposal for a generic interaction with the user icon in the top left.

**Comment by myueksel** [comment]
![color schemes v2](https://user-images.githubusercontent.com/25901307/27793076-cdd6c582-5ffc-11e7-937a-990a06b1c788.png)

**Comment by schluchter** [comment]
@fragsalat Ping! This is now reviewed, please come to Mehmet with any questions. Thanks!

**Comment by fragsalat** [comment]
@myueksel @schluchter You saw the latest header already. I think this is done correct?

**Comment by schluchter** [comment]
@fragsalat Is the header in the PO Prototype the "reference implementation"? Then we can check it out.

**Comment by fragsalat** [comment]
In the prototype are not the ux fixes inside.

**Comment by fragsalat** [comment]
Now you can checkout the latest po-prototype master branch and run `npm i` on the cli.
This will install the latest components.

**Comment by fokusferit** [comment]
@fragsalat @schluchter @myueksel I think this one is done, right ?

**Comment by myueksel** [comment]
Yes
