### ISSUE TITLE
Investigate different font for design system

### ISSUE THREAD

**Issue by schluchter** [fabric-design/scss#46]

**Comment by schluchter** [comment]
- Windows rendering of numbers can be difficult
- Line-height, baselining of font difficult
- Consider loading implementation

**Comment by fokusferit** [comment]
I think @szafranek @myueksel are working on this ?

**Comment by myueksel** [comment]
yes is in progress

**Comment by schluchter** [comment]
@szafranek There are two things we haven't done yet to potentially improve performance of Typekit:

- Longer cache times (https://helpx.adobe.com/typekit/using/optimizing-performance.html)
- Advanced embedding (https://helpx.adobe.com/typekit/using/embed-codes.html)

**Comment by schluchter** [comment]
The decision to replace Acumin with Objektiv MK1 has been taken. I'll close this issue and open a new one for the Typekit performance optimizations.

**Comment by fragsalat** [comment]
@schluchter is the font already available on the typekit so we could use it?

**Comment by schluchter** [comment]
Not yet. We’re working with the third-party team responsible for our Adobe
license to set up a Typekit account that is independent of a person’s
Zalando account. That would also generate a new embed code. Maybe better to
switch everything at once?
Thomas Schlage <notifications@github.com> schrieb am Mo. 9. Okt. 2017 um
16:19:

**Comment by fragsalat** [comment]
Oki doki. Sounds good :)
