### ISSUE TITLE
Table design Update

### ISSUE THREAD

**Issue by myueksel** [fabric-design/scss#51]
Apply to all current table solutions.

**Comment by myueksel** [comment]
![table solutions v4](https://user-images.githubusercontent.com/25901307/27472908-823b43c0-57fd-11e7-9c73-4a9ddf14a552.png)


Invision:
https://zalando.invisionapp.com/d/main/#/console/10454474/240453640/preview

**Comment by schluchter** [comment]
Sprint 10 will test both variants and put it into Design Review again.

**Comment by fragsalat** [comment]
I think this is done. 

@fabric-design/ux could you check it?
https://fabric-design.github.io/styleguide/#/molecules/tables

**Comment by fokusferit** [comment]
Closing it, as it seems done.
